# Generated by Django 3.2 on 2021-05-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_bike_electric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='production_year',
            field=models.DateField(),
        ),
    ]
