# Generated by Django 3.2 on 2021-05-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_bike_production_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='photo',
            field=models.ImageField(default='blog/static/default.png', upload_to='bike_photo'),
        ),
    ]
